export interface UpcomingService {
    id: string
    vehicleId: string
    vehicleName: string
    serviceName: string
    serviceType: 'Maintenance' | 'Inspection' | 'Repair' | 'Oil Change' | 'Tire Rotation'
    dueDate: string
    daysUntilDue: number
    priority: 'Critical' | 'High' | 'Medium' | 'Low'
    status: 'Overdue' | 'Due Soon' | 'Scheduled' | 'In Progress'
    estimatedCost: number
    assignedTechnician?: string
    notes?: string
}

export const upcomingServices: UpcomingService[] = [
    {
        id: 'srv-001',
        vehicleId: 'CHE-TRB-777',
        vehicleName: 'Chevrolet Trailblazer',
        serviceName: 'Engine Oil Change',
        serviceType: 'Oil Change',
        dueDate: '2026-03-10',
        daysUntilDue: 3,
        priority: 'Critical',
        status: 'Overdue',
        estimatedCost: 85,
        assignedTechnician: 'John Smith',
        notes: 'Using synthetic oil',
    },
    {
        id: 'srv-002',
        vehicleId: 'BMW-530-080',
        vehicleName: 'BMW 530XD',
        serviceName: 'Brake Inspection',
        serviceType: 'Inspection',
        dueDate: '2026-03-12',
        daysUntilDue: 5,
        priority: 'High',
        status: 'Due Soon',
        estimatedCost: 150,
        assignedTechnician: 'Maria Garcia',
        notes: 'Check brake pads and rotors',
    },
    {
        id: 'srv-003',
        vehicleId: 'PEU-308-123',
        vehicleName: 'Peugeot 308',
        serviceName: 'Tire Rotation',
        serviceType: 'Tire Rotation',
        dueDate: '2026-03-15',
        daysUntilDue: 8,
        priority: 'Medium',
        status: 'Scheduled',
        estimatedCost: 65,
        assignedTechnician: 'Ahmed Hassan',
    },
    {
        id: 'srv-004',
        vehicleId: 'CHE-TRB-777',
        vehicleName: 'Chevrolet Trailblazer',
        serviceName: 'Air Filter Replacement',
        serviceType: 'Maintenance',
        dueDate: '2026-03-18',
        daysUntilDue: 11,
        priority: 'Medium',
        status: 'Scheduled',
        estimatedCost: 45,
    },
    {
        id: 'srv-005',
        vehicleId: 'REN-MES-555',
        vehicleName: 'Renault Megane',
        serviceName: 'Transmission Fluid Check',
        serviceType: 'Inspection',
        dueDate: '2026-03-20',
        daysUntilDue: 13,
        priority: 'Low',
        status: 'Scheduled',
        estimatedCost: 75,
    },
    {
        id: 'srv-006',
        vehicleId: 'BOB-BOB-789',
        vehicleName: 'Bobcat Loader',
        serviceName: 'Hydraulic System Service',
        serviceType: 'Maintenance',
        dueDate: '2026-03-25',
        daysUntilDue: 18,
        priority: 'High',
        status: 'Scheduled',
        estimatedCost: 400,
        notes: 'Heavy equipment service',
    },
    {
        id: 'srv-007',
        vehicleId: 'BMW-530-080',
        vehicleName: 'BMW 530XD',
        serviceName: 'Battery Health Check',
        serviceType: 'Inspection',
        dueDate: '2026-03-28',
        daysUntilDue: 21,
        priority: 'Low',
        status: 'Scheduled',
        estimatedCost: 0,
    },
    {
        id: 'srv-008',
        vehicleId: 'INDR-SIL-456',
        vehicleName: 'Isuzu Dmax',
        serviceName: 'Full Vehicle Inspection',
        serviceType: 'Inspection',
        dueDate: '2026-03-22',
        daysUntilDue: 15,
        priority: 'Medium',
        status: 'Scheduled',
        estimatedCost: 200,
        assignedTechnician: 'Robert Wilson',
    },
    {
        id: 'srv-009',
        vehicleId: 'BOB-BOB-789',
        vehicleName: 'Bobcat Loader',
        serviceName: 'Tire Condition Assessment',
        serviceType: 'Inspection',
        dueDate: '2026-04-05',
        daysUntilDue: 29,
        priority: 'Low',
        status: 'Scheduled',
        estimatedCost: 0,
    },
    {
        id: 'srv-010',
        vehicleId: 'CHE-TRB-777',
        vehicleName: 'Chevrolet Trailblazer',
        serviceName: 'Coolant Flush',
        serviceType: 'Maintenance',
        dueDate: '2026-04-10',
        daysUntilDue: 34,
        priority: 'Low',
        status: 'Scheduled',
        estimatedCost: 120,
    },
]
