export interface Vehicle {
    vin: string
    licensePlate: string
    make: string
    model: string
    displayName: string
    vehicleType: string
    vehicleGroup: string
    vehicleStatus: string
    assignedPerson?: string
    responsiblePerson?: string
    vehicleManager?: string
    bodyType: string
    transmissionType: string
    fuelType: string
    spareTire: string
    possession: string
}

export const vehicles: Vehicle[] = [
    {
        vin: '1GNDT13S922184641',
        licensePlate: '777TFR',
        make: 'CHEVROLET',
        model: 'TRAILBLAZER',
        displayName: 'Chevrolet Trailblazer',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        bodyType: 'other',
        transmissionType: 'automatic',
        fuelType: 'Gasoline',
        spareTire: 'full size',
        possession: 'owned',
    },
    {
        vin: 'WBANM71010CP17150',
        licensePlate: '080BHB',
        make: 'BMW',
        model: '530XD',
        displayName: 'BMW 530XD',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        bodyType: 'other',
        transmissionType: 'automatic',
        fuelType: 'Diesel',
        spareTire: 'unknown',
        possession: 'operational leasing',
    },
    {
        vin: 'SHSRE6890FU521279',
        licensePlate: '197MPN',
        make: 'HONDA',
        model: 'CR-V',
        displayName: "Sven's CRV",
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        assignedPerson: 'Sven Aulik',
        vehicleManager: 'Aado Mägisoo',
        bodyType: 'multipurpose M1 vehicle',
        transmissionType: 'automatic',
        fuelType: 'Diesel',
        spareTire: 'full size',
        possession: 'owned',
    },
    {
        vin: '61779Y280',
        licensePlate: '',
        make: 'Super73',
        model: 'S1',
        displayName: 'Electric Scooter',
        vehicleType: 'Electric scooter',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        assignedPerson: 'Aado Mägisoo',
        bodyType: 'direct',
        transmissionType: 'Electric',
        fuelType: 'Electric',
        spareTire: 'none',
        possession: 'owned',
    },
    {
        vin: 'VF3MRHNSUKS465124',
        licensePlate: 'MN8775',
        make: 'PEUGEOT',
        model: '3008',
        displayName: 'Võtmevaba sisenemine',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        bodyType: 'other',
        transmissionType: 'automatic',
        fuelType: 'Gasoline',
        spareTire: 'unknown',
        possession: 'owned',
    },
    {
        vin: 'TMBCJ9NP1K7061906',
        licensePlate: '133FXP',
        make: 'SKODA',
        model: 'SUPERB',
        displayName: 'Skoda Superb',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        bodyType: 'saloon',
        transmissionType: 'automatic',
        fuelType: 'Diesel',
        spareTire: 'unknown',
        possession: 'owned',
    },
    {
        vin: 'VF3M45GFULS315652',
        licensePlate: '848HRF',
        make: 'PEUGEOT',
        model: '5008',
        displayName: 'Peugeot 5008',
        vehicleType: 'Passenger car',
        vehicleGroup: 'Sõiduauto',
        vehicleStatus: 'Active',
        responsiblePerson: 'Aado Mägisoo',
        vehicleManager: 'Aado Mägisoo',
        bodyType: 'multipurpose M1 vehicle',
        transmissionType: 'automatic',
        fuelType: 'Gasoline',
        spareTire: 'compressor + tire fix kit',
        possession: 'operational leasing',
    },
    {
        vin: 'VF3MCYHZULS322001',
        licensePlate: '081LKV',
        make: 'PEUGEOT',
        model: '3008',
        displayName: 'Peugeot 3008',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        bodyType: 'multipurpose M1 vehicle',
        transmissionType: 'automatic',
        fuelType: 'Diesel',
        spareTire: 'unknown',
        possession: 'financial leasing',
    },
    {
        vin: 'VF1EM0U0A31194040',
        licensePlate: '001TFR',
        make: 'RENAULT',
        model: 'MEGANE',
        displayName: 'Renault Megane',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        assignedPerson: 'Indrek Siitan',
        bodyType: 'convertible',
        transmissionType: 'automatic',
        fuelType: 'Gasoline',
        spareTire: 'unknown',
        possession: 'owned',
    },
    {
        vin: 'WDB9066331S750858',
        licensePlate: 'KN5647',
        make: 'MERCEDES BENZ',
        model: 'SPRINTER',
        displayName: 'Mercedes Sprinter',
        vehicleType: 'Light commercial vehicle / van',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        bodyType: 'other',
        transmissionType: 'automatic',
        fuelType: 'Diesel',
        spareTire: 'unknown',
        possession: 'owned',
    },
    {
        vin: 'WBA5L5102HG098005',
        licensePlate: 'EUB-520',
        make: 'BMW',
        model: '520D XDRIVE',
        displayName: 'BMW 520D',
        vehicleType: 'Passenger car',
        vehicleGroup: '',
        vehicleStatus: 'Active',
        assignedPerson: 'Sven Aulik',
        bodyType: 'station wagon',
        transmissionType: 'automatic',
        fuelType: 'Diesel',
        spareTire: 'unknown',
        possession: 'owned',
    },
]
